name = "onboarding"
main = "src/index.js"
compatibility_date = "2026-04-22"
workers_dev = true

[vars]
ASANA_DUPLICATE_MODE = "project"
ASANA_TEMPLATE_PROJECT_GID = "1213638268637823"
ASANA_DUPLICATE_INCLUDE = "task_subtasks,task_attachments,task_notes,task_assignee,task_dates,task_dependencies,task_followers,task_projects,task_tags,members,notes,forms,rules"
ASANA_CUSTOM_FIELD_MAP = "{}"
